version: '3.8'

services:
  fastapi:
    image: dndrag-fastapi
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./fastapi:/app

  test:
    image: dndrag-test
    command: [ "python", "main.py" ]
    depends_on:
      - fastapi
    networks:
      - app-network
    volumes:
      - ./test:/app

  upload-dataset:
    image: dndrag-test
    command: [ "python", "dataset.py" ]
    depends_on:
      - fastapi
    networks:
      - app-network
    volumes:
      - ./test:/app

networks:
  app-network:
    driver: bridge
